from __future__ import annotations

import re
from typing import Tuple, List, Dict

from .prompt import PartEvoPrompt
from ...base import LLM, SampleTrimmer, Function, Program


class PartEvoSampler:
    """
    The MLESSampler serves as the interface for interacting with the LLM.
    It handles the execution of sampling requests and uses regular expressions
    to extract structured thoughts, image descriptions, and executable code
    from raw LLM text outputs.
    """
    def __init__(self, sampler: LLM, template_program: str | Program):
        """
        Initialize the sampler with an LLM engine and a code template.

        :param sampler: The LLM instance used to generate responses.
        :param template_program: A template structure used to reconstruct
                                 Function objects from raw code strings.
        """
        self._sampler = sampler
        self._template_program = template_program

    def get_thought_and_function(self, prompt: str, image64s: List = None, messages: List = None) -> tuple[
        str | None, Function | None, str]:
        """
        Main sampling method: Sends a prompt to the LLM and extracts both
        the algorithmic reasoning (thought) and the resulting code.

        :return: A tuple containing (extracted_thought, Function_object, raw_response_string).
        """
        # Call the LLM to get a raw response
        response = self._sampler.draw_sample(prompt, image64s=image64s, messages=messages)
        # Parse the algorithmic concept (thought) from the response
        thought = self.__class__.trim_thought_from_response(response)
        # Extract the code block and convert it into an executable Function instance
        code = SampleTrimmer.trim_preface_of_function(response)
        function = SampleTrimmer.sample_to_function(code, self._template_program)
        return thought, function, response

    def get_image_description(self, prompt: str, image64s: List = None, messages: List = None):
        """
        Used for multimodal feedback loops. Extracts a textual analysis of
        visual data (e.g., control trajectories) generated by the LLM.

        :return: A tuple containing (extracted_description, raw_response_string).
        """
        response = self._sampler.draw_sample(prompt, image64s=image64s, messages=messages)
        # Parse descriptions specifically wrapped in double curly braces
        description = self.__class__.trim_description_from_response(response)
        return description, response

    def get_reflection(self, prompt: str, messages: List = None):
        response = self._sampler.draw_sample(prompt, image64s=None, messages=messages)
        # Parse descriptions specifically wrapped in double curly braces
        reflection = self.__class__.trim_reflection_from_response(response)
        return reflection

    @classmethod
    def trim_thought_from_response(cls, response: str) -> str | None:
        """
        Extracts content within single curly braces {like this}.
        This corresponds to the 'algorithmic concept' requested in MLESPrompt.
        """
        try:
            pattern = r'\{.*?\}'  # Compared with r'\{(.*)\}'
            bracketed_texts = re.findall(pattern, response)
            return bracketed_texts[0]
        except:
            return None

    @classmethod
    def trim_reflection_from_response(cls, response: str) -> str | None:
        """
        Extracts the content inside the first occurrence of < > brackets.
        """
        try:
            # 1. Regex pattern explanations:
            # <<      : Match literal '<<'
            # (       : Start capturing group
            # [\s\S]*?: Match any character (including newlines), non-greedy (*?)
            # )       : End capturing group
            # >>      : Match literal '>>'
            pattern = r'<<([\s\S]*?)>>'

            # Note: [\s\S] includes newlines, so re.DOTALL is technically redundant but harmless.
            bracketed_texts = re.findall(pattern, response)

            if bracketed_texts:
                # 2. Return the first match and strip whitespace
                return bracketed_texts[0].strip()
            return None

        except Exception as e:
            # It's better to log the full error for debugging
            print(f"Error in trim_tips_from_response: {e}")
            return None

    @classmethod
    def trim_description_from_response(cls, response: str) -> str | None:
        """
        Extracts content within double curly braces {{like this}}.
        Used for multi-line textual descriptions of visual results.
        """
        try:
            # Adjust the pattern to match multi-line text within braces
            pattern = r'\{\{.*?\}\}'  # Non-greedy match for double braces
            bracketed_texts = re.findall(pattern, response, re.DOTALL)  # Use re.DOTALL to match newlines
            return bracketed_texts[0] if bracketed_texts else None
        except Exception as e:
            print(f"Error: {e}")
            return None
